### ISSUE TITLE
VLC black screen

### ISSUE THREAD

**Issue by radojko** [olegk0/xf86-video-fbdev#1]
VLC doesn't show video but black screen.

This patch helps but video doesn't cover full VLC window(resized is for about 30% inside VLC window), :

--- /install/xf86-video-fbdev-master/src/video.c.orig
+++ /install/xf86-video-fbdev-master/src/video.c
@@ -634,7 +634,7 @@
     for(i = 0; i < XVPORTS; i++)
             adapt->pPortPrivates[i].val = i;
-    XVport->colorKey = 0x00020202;
-    XVport->colorKey = 0;
   XVport->videoStatus = 0;
   XVport->lastPort = -1;

**Comment by olegk0** [comment]
old version
