### ISSUE TITLE
AIGLX error

### ISSUE THREAD

**Issue by xoox** [olegk0/xf86-video-fbdev#2]
I just installed this driver, but it sames failed. The parts of xorg log showing as here.

```
[ 72334.726] (II) RKFB(0): Init mode: current
[ 72334.741] (==) RKFB(0): Backing store enabled
[ 72334.742] (==) RKFB(0): DPMS enabled
[ 72334.742] (II) RKFB(0): HW:Initialize overlays
[ 72334.742] (EE) RKFB(0): HW:Error init RkOverlays:-19
[ 72334.742] (II) RKFB(0): XV:Init begin
[ 72334.742] (EE) RKFB(0): XV:Not found overlay
[ 72334.742] (EE) RKFB(0): Rk30MaliDRI2_Init: Overlay not found!
[ 72334.757] (II) Loading sub module "dri2"
[ 72334.757] (II) LoadModule: "dri2"
[ 72334.757] (II) Module "dri2" already built-in
[ 72334.758] (II) RKFB(0): HW overlay for 3D not usable
[ 72334.758] (II) RKFB(0): [DRI2] Setup complete
[ 72334.758] (II) RKFB(0): [DRI2]   DRI driver: rk30-mali
[ 72334.758] (==) RandR enabled
[ 72334.796] (II) SELinux: Disabled on system
[ 72334.801] (EE) AIGLX error: dlopen of /usr/lib/arm-linux-gnueabihf/dri/rk30-mali_dri.so failed (/usr/lib/arm-linux-gnueabihf/dri/rk30-mali_dri.so: cannot open shared object file: No such file or directory)
[ 72334.802] (EE) AIGLX: reverting to software rendering
```

Would you please give any idea to fix this?

Here's some extra information.
Board: [Marsboard RK3066](http://marsboard.org/marsboard_rk3066_feature.html)
OS: Debian 8.5
kernel: [rockchip-marsboard-rk3066-linux-3.0.8](https://github.com/powermcu/rockchip-marsboard-rk3066-linux-3.0.8)
mali kernel driver: integrated to the kernel. version r3p2.
[sunxi-mali](https://github.com/linux-sunxi/sunxi-mali) installed with VERSION=r3p2-01rel1

**Comment by olegk0** [comment]
This driver works with the kernel https://github.com/olegk0/rk3x_kernel_3.0.36 and library https://github.com/olegk0/librklayers
